### ISSUE TITLE
Split "how to install" article into 3 versions spanning each platform

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#151]
This originated from [#126](https://github.com/bitcoin-solutions/multibit-hd/issues/126) and [#242](https://github.com/bitcoin-solutions/multibit-hd/issues/242) in MultiBit HD so see there for the relevant content.
Overall the user process would be:

* download and install MBHD as usual
* while waiting visit the post-install article(s)
* select the script you want to run to set up the Linux environment in an optimal manner

The articles should be extensible so that experts can modify them to suit best practices.

**Comment by gary-rowe** [comment]
Need to add the following observation for Slackware Linux. The USB udev rule (`/etc/udev/rules.d`) may need to be set to 
```
MODE="0666", GROUP="dialout"
```

**Comment by gary-rowe** [comment]
Change of focus for this issue. We require the following files: `how-to-install-windows.html`, `how-to-install-osx.html`, `how-to-install-linux.html`. The individual sections from the original `how-to-install` should be split across these files.

Finally a link to each should be present below the download buttons to give the users something to read while they wait for the installer to arrive.

Each page should contain a link to the "Check your digitial signatures" blog article after the installer has downloaded section to encourage security checking.

**Comment by m1rr0rm3** [comment]
How do I get off this mailing list?  I am no longer participating.

Chris
64bithost@gmail.com

**Comment by gary-rowe** [comment]
@m1rr0rm3 You just need to "unwatch" this gitHub repo (top right corner).

**Comment by gary-rowe** [comment]
Since this is live on beta I'll close it here.
