### ISSUE TITLE
Support HSTS headers in responses

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#153]
Update the Dropwizard/Jetty responses to include:
```
Strict-Transport-Security: max-age=31536000; includeSubDomains
```
This is to keep MultiBit.org in line with current Bitcoin.org requirements

In addition the server configuration (in the HTTPS section only) should include

```
Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"
```
This is in line with OWASP recommendations: https://www.owasp.org/index.php/HTTP_Strict_Transport_Security

**Comment by gary-rowe** [comment]
We need to perform some additional actions in the `httpd.conf` for the VirtualHosts sections to remove all SSL references. From a [StackOverflow answer](http://unix.stackexchange.com/a/162500/19023):
```
...
<VirtualHost your.website.example.com:443>
    DocumentRoot /var/www/directory
    ServerName your.website.example.com
    ...
    SSLEngine on
    ...
    SSLProtocol all -SSLv2 -SSLv3
    ...
</VirtualHost>
```
Needs to be set for *all* `VirtualHost` entries.

**Comment by bitcoin-solutions** [comment]
I have added this to all our port 443 virtual hosts and deployed it to our live servers.
(Adding it to the port 80 hosts nuked httpd so I've not done it for them.)

**Comment by gary-rowe** [comment]
![screen shot 2015-01-28 at 19 31 15](https://cloud.githubusercontent.com/assets/342133/5945146/55535438-a724-11e4-9887-40c3034e0820.png)
