### ISSUE TITLE
Ho perso il portafoglio MultiBit (ITA)

### ISSUE THREAD

**Issue by IGunzI** [bitcoin-solutions/multibit-website#155]
Il hard disk del mio notebook si è rotto e ho dovuto cambiarlo , ma dopo averlo cambiato il mio MultiBit wallet non è più quello di prima . Cosa potrei fare? So ancora il mio vecchio ID del portafoglio e quanti soldi ci sono dentro , so anche da chi e quando sono arrivati . Non avevo la password e non ho potuto fare il backup del portafoglio . Aiutatemi vi prego!

**Comment by gary-rowe** [comment]
Closing as this is the wrong issue repo for this problem.
