### ISSUE TITLE
missing wallet

### ISSUE THREAD

**Issue by mrsurftheweb** [bitcoin-solutions/multibit-website#156]
I have 4 set up in total- other 3 are password protected. Opened this 4th one as a new one  as brother wanted me to hold some funds for him in btc so set it up but didn't create a password (mistake perhaps now thinking of it) but was working fine this evening until I put it in a folder and then when I tried to open the 4 wallets, only the 3 older ones appeared?? - windows 8 operating system

**Comment by bitcoin-solutions** [comment]
Moving wallets around can be problematic as there are other 'support' files MultiBit needs.
('wallet-name'.info and everything in the 'wallet-name'-data directory.

If you also copy those files to the new wallet location you should be able to do a 'File | Open of the wallet in the new directory and it will sync

**Comment by mrsurftheweb** [comment]
I can't find the files for the 4th wallet- i did not move it myself - I did a file search and I only show the 3 wallet files.  Is there a back up somewhere?  The missing wallet has a fair amount of bitcoin in it.  Is there any other way to find and recover it?  Could someone hacked my computer and stole it??
