### ISSUE TITLE
Require update to Linux gotchas for MultiBit Classic

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#158]
Issue [#325](https://github.com/jim618/multibit/issues/325) in MulitBit Classic contains information that is worth placing on the main website help section.

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by bitcoin-solutions** [comment]
'Linux gotchas' note appearing on install page ok.
(Not pushed to beta.multibit.org yet - waiting for beta 5 release)

Closing
