### ISSUE TITLE
Rename "seed phrase" as "wallet words" throughout the MBHD help

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#159]
This is for consistency in terminology in the documentation and application.

This only applies to Help articles in HD 0.1, blog and other references are exempt.

**Comment by gary-rowe** [comment]
Left a few "(seed phrase)" entries in the help to assist with other wallets' nomenclature.

Ready for review and close.

**Comment by bitcoin-solutions** [comment]
The screen shots on the 'create wallet' page still refer to 'seed phrase' which is a bit dissonant. This is worth fixing I think as it will be a havily trafficked page.

**Comment by bitcoin-solutions** [comment]
Other than that it all looks consistent with usage of 'wallet words'

**Comment by gary-rowe** [comment]
OK, I'll close this since #161 will cover screen shots.
