### ISSUE TITLE
Update screenshots to show off Beta 5 features

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#161]
We need to refresh the screenshots to cover the new features introduced in Beta 5:

* Trezor support
* Sign/verify
* Units
* Payments
* Exchange
* Languages
* Wallet words
* Transaction details
* etc

**Comment by jim618** [comment]
Also it would be good to remove the support@bitcoin-solutions.co.uk from the contacts screen as the recommended channel for help is the internal help -> stackexchange -> github, not email

**Comment by jim618** [comment]
As updated screenshots have been pushed recently to beta.multibit.org I am closing this.
