### ISSUE TITLE
Detect Win32 or Win64 and ensure button downloads correct version

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-website#164]
The user agent string needs to look for win32 or win64 and provide a link to the most appropriate download. A user won't be able to quickly tell which is correct for them otherwise.

This does not apply to Mac (64 bit only) or Linux (external JVM).

Here's a handy user agent list: http://stackoverflow.com/questions/1741933/detect-64-bit-or-32-bit-windows-from-user-agent-or-javascript

**Comment by gary-rowe** [comment]
This is too complicated as it stands. A better approach, given that win64 is more common than win32, is to provide a link to the win32 edition alongside the supporting links for each button.

Closing.
