### ISSUE TITLE
Help I cant see my btc and blockchain show 21 confirmations

### ISSUE THREAD

**Issue by konshus** [bitcoin-solutions/multibit-website#167]
Hi this is my wallet 15G2NH3AH6cnykCXZvFzj7qunsjoFVS5RK i added some money, and the statuse wouldnt change, so i went on blockchain and the transaction was ok and had 21 confirmations, and now  my btc wallet shows 0 and doesnt finish synchronizing.
![btcwallet](https://cloud.githubusercontent.com/assets/10930880/6116838/d4a8ea38-b064-11e4-9fbe-24371afb0644.PNG)
![btcwallet1](https://cloud.githubusercontent.com/assets/10930880/6116865/00ce0918-b065-11e4-860d-92b03acae437.PNG)

**Comment by konshus** [comment]
Now i dont know where my money is and I need it, please reply with solution

**Comment by konshus** [comment]
ok, everything is ok now, thank you.

**Comment by bitcoin-solutions** [comment]
Most likely just the delay whilst syncing.
Closing
