### ISSUE TITLE
Provide a script to resize screenshot images to suitable width for internal help in MBHD

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#168]
Need to ensure that full-size screenshot images do not exceed `width:670px` (based on the internal help for MBHD) to allow for correct live rendering in the internal help. 

This will also reduce the image footprint which is a Good Thing.

The implementation should be automatic as part of the Maven build under the same profile as the Atom feed generation. 

It can should re-use the `resizeSharp` approach in MultiBit HD as seen during its caching operations in `HelpScreenView`.

**Comment by gary-rowe** [comment]
The resulting images are a bit fuzzy and are only really fit for very small devices. I'm going to defer this issue until we've had some feedback from users.

**Comment by ekankyesme** [comment]
hii

**Comment by jim618** [comment]
Screenshots have been removed from the help so this issue is no longer required.
Closing
