### ISSUE TITLE
My bitcoins are gone!!

### ISSUE THREAD

**Issue by granddomains** [bitcoin-solutions/multibit-website#170]
Hi,

I was using Multibit in order to send and receive bitcoin, now they are gone.
I started a transaction now but I saw a square, after that they just gone!! Where did they go!!!!
Please, help!

**Comment by gary-rowe** [comment]
Please note that this GitHub issue database is for issues regarding the MultiBit.org website, not the desktop application. 

Can you verify that you have read the help articles: https://multibit.org/help.html, in particular: https://multibit.org/en/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html

**Comment by jim618** [comment]
Closed - most likely the help sorted it.
