### ISSUE TITLE
Consider link to video in FAQ

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#171]
Review this video for inclusion in the FAQ: https://www.youtube.com/watch?v=YIVAluSL9SU

**Comment by gary-rowe** [comment]
Video gives a great explanation of why Bitcoin is important without being preachy or patronising. Added link accordingly.

Ready for review and close.

**Comment by jim618** [comment]
Very approachable video.
Checked link on FAQ.
Closing.
