### ISSUE TITLE
Add articles on Change PIN, About MultiBit HD

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#175]
I've added a couple of short articles to the help on Change PIN and the About screen for completeness.
Awaiting reviewing and closing.

**Comment by gary-rowe** [comment]
Made some slight edits that could be useful for a "create wallet with Trezor" article.

If you're OK with them then it's good to close.

**Comment by jim618** [comment]
Fine by me.
Closing
