### ISSUE TITLE
Add MultiBit Classic donation address to Privacy | Security

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#176]
Added a section in the Privacy policy about how we use the MultiBit Classic donation address to bitcoin sign the release notes. Plus a how-to on how to verify them.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Made some minor edits. If you're OK with them then it's good to close.

**Comment by jim618** [comment]
Ok.Closed.
