### ISSUE TITLE
Transaction could not be created without exceeding max size

### ISSUE THREAD

**Issue by pdtan** [bitcoin-solutions/multibit-website#178]
While sending large amount, I got these messages:
The send of your bitcoin failed. The error was "java.lang.IllegalArgumentException Transaction could not be created without exceeding max size: 250754 vs 102400".
The send of your bitcoin failed. The error was "java.lang.IllegalArgumentException Transaction could not be created without exceeding max size: 144605 vs 102400".
The send of your bitcoin failed. The error was "java.lang.IllegalArgumentException Transaction could not be created without exceeding max size: 111149 vs 102400".

and it took too much time to send large amount of BTC.

**Comment by jim618** [comment]
If you are trying to consolidate lots of smaller amounts this could very well be a genuine limit of the Bitcoin system. 102400 bytes is about 10% of the maximum size (currently) of a block.

The way round it, which I expect you have already worked out, is to send a few, smaller tx to consolidate.

**Comment by jim618** [comment]
The time delay you are experiencing will be because you probably have 1 thousand inputs that MultiBit has to cryptographically sign. This is a relatively slow operation as it has to do quite a lot of calculation. 
There isn't really a way round this.
