### ISSUE TITLE
Add link to early-access Release 0.1 as alert banner in main site

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#179]
A blue (info) banner should be present on the live site with the following wording:

"MultiBit HD Release 0.1 will be replacing MultiBit Classic soon. You can [start using it now](https://beta.multibit.org)"

**Comment by gary-rowe** [comment]
Added blue alert (more visible) to encourage users to make the switch. 

![screen shot 2015-05-18 at 22 46 31](https://cloud.githubusercontent.com/assets/342133/7691103/cac1dcda-fdaf-11e4-81a0-1b11c22ce87f.png)

This is present on `develop` so when Release 0.1 is released for 24 hours we can push it to the live site to encourage greater use.

Ready for review and close.

**Comment by jim618** [comment]
Looks fine.
Not pushed to multibit.org yet obviously.
Closing
