### ISSUE TITLE
Update multibithd.org to point to beta.multibit.org

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#181]
Various search engines are getting a bit confused with multibithd.org acting as its own site offering a primitive version of the beta site. 

It should redirect to the main site.

**Comment by gary-rowe** [comment]
Updated [multibithd.org](http://multibithd.org) and [multibithd.com](http://multibithd.com) to point to beta.multibit.org. 

At present multibithd.org is experiencing a 503 Server unavailable error due to hosting issues so redirecting may not be working until that is resolved.

Ready for review and close.

**Comment by jim618** [comment]
Checked both domains redirect to beta.multibit.org.
Closing
