### ISSUE TITLE
I lost bitcoin, please help me!

### ISSUE THREAD

**Issue by rendra99** [bitcoin-solutions/multibit-website#182]
I just closed my wallet, but my backup does not exist, the word "wallet" I was looking for did not exist at all drives, what next solution?
The missing my bitcoin address
1BTgaL12v7tWwRnoRxDVUQuyudFBH8UCxE

**Comment by gary-rowe** [comment]
Have a read of this article (and links from it): https://multibit.org/help.html. If you are still unable to resolve the issue, follow the support instructions at the end of the page.

Since this is not the MultiBit Classic issue database, I'll close this.
