### ISSUE TITLE
Help selector page should encourage upgrade from Classic to HD

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#191]
The [help selector page](https://beta.multibit.org/help.html) should be used to encourage users to upgrade.

**Comment by gary-rowe** [comment]
Added link to upgrade process below MultiBit Classic.

![screen shot 2015-05-10 at 13 01 36](https://cloud.githubusercontent.com/assets/342133/7554161/05eaca84-f715-11e4-980e-5007c465e238.png)

Ready for review and close.

**Comment by jim618** [comment]
Looks ok. We'll probably have to nag in more ways than this but it's a good start.
Closing
