### ISSUE TITLE
Write Release 0.1 blog article

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#192]
Article needs to provide a complete feature list, including:

Non-technical list

* no worrying about losing private keys any more - use your "wallet words" (seed phrase) to restore them
* easy installer with semi-automatic update (you choose when)
* intuitive user interface 
* fast and lightweight block chain download just like MultiBit Classic (SPV) about 25Mb overall
* support for Trezor hardware wallet out of the box
* private Contacts database with private notes 
* private Payments database with integrated exchange rates
* adjustable fees
* adjustable units (support for bits, ubits, millis etc)
* integrated exchange rates from multiple exchanges to support national currencies
* export transactions with spot rates to a financial package in standard CSV format
* themes to suit different lighting conditions
* detailed integrated Help if you get stuck
* available in many languages (want to contribute?)

Technical list

* open source under modified MIT licence
* pure SPV so no intermediate servers
* random peer discovery
* support for Tor out of the box
* all data is encrypted locally using entropy gathered from your wallet words (12, 18 or 24)
* hierarchical deterministic (HD) wallet support BIP32 and BIP44 (account 1 only in each case because it's SPV)
* all data automatically backed up to a location of your choice (encrypted)
* detailed transaction information
* support for BIP21/72 links and Payment Protocol
* multiple block explorers
* integrated error reporting

Anything else to add?

**Comment by gary-rowe** [comment]
Created a first draft for interim review.

**Comment by jim618** [comment]
Reviewed. Looks good. Closing.
