### ISSUE TITLE
Update Help for Sounds to include possible missing alert sound

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#194]
User feedback has indicated the following should be addressed:

#### I can hear the coins but not the alerts

You should be hearing the default system beep. However, it may be turned off by default on your system. 

On Windows [use this guide in reverse](http://www.thewindowsclub.com/disable-system-beep-windows-7-8) to enable the system beep.

On OS X, select Apple | System Preferences | Sounds. Note that unchecking the "User interface sounds" doesn't disable all sound. However sliding the "Alert Volume" option all the way to the left (minimum), together with unchecking the other options will disable the beep.

**Comment by gary-rowe** [comment]
Updated with more information

Ready for review and close.

**Comment by jim618** [comment]
Nice bit of extra help for user's beep needs.
Closing
