### ISSUE TITLE
Updated screenshots need some responsive layout tweaking

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#195]
I have updated the screenshots on the landing page but cannot get the responsive layout right for 10x8 screens. There is plenty of room on the RHS of the images but the 'MBHD characteristics' text always sits underneath it.

Given to Gary  . . . 

:-)

**Comment by gary-rowe** [comment]
Just a missing </div>.

Ready for review and close.

**Comment by jim618** [comment]
Looks good.
Closing.
