### ISSUE TITLE
Help needs updating - new 'report error' button

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#197]
At the bottom of the help index is a 'how to report an issue' section.
We should remove this or change it to get users to use the 'Report issue' button where possible.

**Comment by gary-rowe** [comment]
Added "offline help" article and updated contents page accordingly. 

Ready for review and close.

**Comment by jim618** [comment]
Yup all looks good, including the new 'how to use the help' article.
Closing
