### ISSUE TITLE
MBHD Restore password help out of date

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#201]
As we have changed the text on the 'Select Option' page the help needs updating to use the labels e.g.
"I have lost my password' rather than 'Restore password from seed'

**Comment by jim618** [comment]
Updatd to match current MBHD Select Option text

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified OK. Closing.
