### ISSUE TITLE
Improve restore from backup for Trezor help

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#205]
It's a bit confusing that there are two ways to restore a Trezor zip backup - hard from zip file.
Soft BIP44 wallet probably from a seed but you can use a zip backup.

Needs a bit more explanation in the help

**Comment by gary-rowe** [comment]
Added article to cover the Trezor restore procedures. After running up a local copy of the site use http://localhost:8888/en/help/hd0.1/restore-hardware-wallet.html

Ready for review and close.

**Comment by jim618** [comment]
Yes this reads fine.
It introduces the nomenclature of 'hard' and 'soft' wallets which I think is unavoidable so I think we should just consider this terminolgy 'official now'.

I have also updated a few mentions of 'seed phrase' in the password recovery article so have a quick check of that.

Closing.
