### ISSUE TITLE
Promote the GitHub repo on the Downloads page

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#206]
We should provide a clearer link (and perhaps a Star/Watch button) to the GitHub repo on the downloads page.

**Comment by gary-rowe** [comment]
I've adjusted the text slightly on the Thank You pages. Here's an example:

![screen shot 2015-05-31 at 13 07 35](https://cloud.githubusercontent.com/assets/342133/7901871/0b96c8f2-0796-11e5-9c42-e4949eb60661.png)

Ready for review and close.

**Comment by jim618** [comment]
This works but now Ghostery highlights this (and blocks it by default) as a tracker.

We don't use trackers anywhere else and in our privacy statement we say:
"We do not use tracking cookies but third party providers might."

Whilst technically this is true it is sailing close to the wind.

I would prefer we don't have it on as it gives the IP address of everyone who downloads to github.

**Comment by gary-rowe** [comment]
Agreed. I've removed them due to privacy.

Ready for review and close.

**Comment by jim618** [comment]
Yup all looks good. Checked for Win/osx/linux that the github like button has gone.
