### ISSUE TITLE
'Learn about the built in help' article too technical

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#207]
The article in the help about how to use the help is a bit technical.
It talks about offline this and https that which to most people is gobble-de-gook.

I suggest we simplify it to just explain the navigation controls and don't mention the technicalities (except perhaps as a one liner near the bottom to say 'if there are any problems accessing the help on multibit.org, a local copy is used')

**Comment by jim618** [comment]
Simplified article slightly to remove technical words.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Looks good to me. Closing.
