### ISSUE TITLE
Privacy policy link on bottom of Thankyou page is broken

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#208]
The Privacy policy link on the bottom of the 'Thankyou for downloading" page is broken (404).
It points to:

http://localhost:8888/en/help/hd0.1/privacy.html

**Comment by gary-rowe** [comment]
Fixed the missing / causing the problem.

Ready for review and close.

**Comment by jim618** [comment]
Verified working.
Closing.
