### ISSUE TITLE
Improved restore password help article

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#210]
Require more detail on restore password, similar to what is available in MultiBit Classic.

**Comment by gary-rowe** [comment]
Added more detail to the restore password article. However there is a section containing a script that may not be valid and needs review/edit to give correct information.

Ready for review and close.

**Comment by jim618** [comment]
Updated to remove the section on script recovery - not applicable for MBHD.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Agreed (as per our conversation).

Closing.
