### ISSUE TITLE
Explain for common browsers how to associate bitcoin: with MBHD

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#212]
Explain for common browsers how to associate bitcoin: with MBHD

**Comment by gary-rowe** [comment]
This is covered in the [Linux installation guide](https://multibit.org/en/help/hd0.1/how-to-install-linux.html) where it is most likely to be encountered.

See near the end.

OK to close?

**Comment by jim618** [comment]
Looks fine and this is the page to put it on.Closing
