### ISSUE TITLE
MultiBit Classic requires help on escaping Java 6 on OS X Yosemite

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-website#214]
In lieu of an updated installer providing auto-update we need instructions for avoiding Java 6. This is necessary since Java 6 does not run on Yosemite.

The fix is simple: Open Terminal and type 

```shell
cd /Applications/MultiBit.app/Contents/Resources/Java
java -jar multbit-exe.jar
```

**Comment by gary-rowe** [comment]
Added more detail to installer page and added it to the contents page. It isn't necessary to fall back to the `java -jar` technique since the Java 6 workaround works on Yosemite.

Ready for review and close.

**Comment by jim618** [comment]
Looks fine. closing.
