### ISSUE TITLE
Add more detail on logs to files.html

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#215]
We could do with a bit more information on manually working with log files and uploading stack traces in case of situation where the crash reporter isn't available.

**Comment by jim618** [comment]
This is for example when the JRE fails, so the user cannot run MultiBit HD (hence the how-to has to be in the help)

**Comment by gary-rowe** [comment]
Added some more information. 

Ready for review and close.

**Comment by gary-rowe** [comment]
Bump prior to live release today.

**Comment by jim618** [comment]
The section on logs is now merged to master and appears in the 'File descriptions'.
Closing
