### ISSUE TITLE
The 'how to check digital signatures' refers to the old website

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#216]
The blog article:
http://localhost:9090/blog/2013/07/24/how-to-check-signatures.html

refers to the old multibit.org  design where the sigs were on the landing page. Needs a refresh.

**Comment by gary-rowe** [comment]
Updated the article accordingly. It now references MultiBit HD 0.1.0 and the download page.

Ready for review and close.

**Comment by jim618** [comment]
Yup  now references the multibit.org download page directly rather than landing page. Closing.
