### ISSUE TITLE
Font Awesome not loading under NoScript

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#217]
Posted in MBHD repo by @wodry

https://github.com/bitcoin-solutions/multibit-hd/issues/617

Inline copy:

When visiting https://multibit.org, on the right side the bullets of the list "Why choose MultiBit HD ?" are shown as strange symbols, see screenshot.

Environment:
Debian Jessie 64 Bit
Iceweasel 31.7.0
NoScript Extension that blocks javascript from multibit.org, ajax.googleapis.com, bootstrapcdn.com and fonts from fonts.gstatic.com and maxcdn.bootstrapcdn.com etc.
Using Proxy privoxy

A good website should work without (third party) JavaScript, fonts etc., IMHO.

![multibithd](https://cloud.githubusercontent.com/assets/8447873/8235555/f2f2e9e2-15e2-11e5-9f3a-7ec1104daf7d.png)

**Comment by gary-rowe** [comment]
Yeah, this is a side-effect of NoScript preventing Font Awesome from being downloaded. 

I'll replace the FA icons with bullets for maximum compliance with NoScript browsers.

**Comment by gary-rowe** [comment]
I've modified the NoScript behaviour to ensure the list style is suitable. It's slightly different to the JS enabled version but looks fine in situ:

![screen shot 2015-06-18 at 22 06 39](https://cloud.githubusercontent.com/assets/342133/8242314/6942dbfc-1606-11e5-992d-a9e868bddde3.png)

This has been updated for the [FR](http://localhost:8888/fr/index.html) and [JA](http://localhost:8888/ja/index.html) locales.

Ready for review and close.

**Comment by wodry** [comment]
Your link http://localhost:8888/fr/index.html does not work for me, of course. So I am wondering how to review. I checked https://multibit.org/fr/index.html but there is still the issue, see screenshot.
![multibithd](https://cloud.githubusercontent.com/assets/8447873/8246549/b2dfe766-1640-11e5-8cab-322afb7868f5.png)

**Comment by gary-rowe** [comment]
Hi @wodry. Yeah, those links are for localhost:8888 when running the website locally. It's a very similar process to running MultiBit HD from within the IDE as you've done before.

Instructions are in the README: https://github.com/bitcoin-solutions/multibit-website/blob/develop/README.md

**Comment by wodry** [comment]
Please someone else build the website and review. I already retired from my layman beta tester dev role :)

**Comment by jim618** [comment]
I'll do it.
:-)

**Comment by jim618** [comment]
Checked by disabling javascript (Safari, Mac) and see bullets. Closing.
