### ISSUE TITLE
Broken link in Atom feed for "bip32-wallet-compatibility"

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#218]
The Atom feed shows a link of: https://multibit.org/en/blog/2015/03/10/bip32-wallet-compatibility.html which 404s.

The correct link is https://multibit.org/blog/2015/04/14/bip32-wallet-compatibility.html.

**Comment by gary-rowe** [comment]
Manual correction. This should withstand a rebuild from the AtomBuilder during the next release but worth keeping an eye on.

Ready for review and close.

**Comment by jim618** [comment]
Checked correct link on blog contents page. Closing
