### ISSUE TITLE
Change 'block chain' to 'blockchain' in FAQ

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#220]
In the FAQ we use the term 'block chain' with a space.

Mainly due to the 'rebranding' of bitcoin -> blockchain in some circles I think we should change all the 'block chain' references to 'blockchain'.

There are several in the FAQ but probably some others hiding away on other pages.

**Comment by gary-rowe** [comment]
Agreed I've been trying to use the "block chain" terminology in new articles but backfilling would be useful.

**Comment by gary-rowe** [comment]
All references updated (including Reset Block chain and transactions" in anticipation of 0.5.19 using that terminology).

Ready for review and close.

**Comment by jim618** [comment]
I am still seeing "block chain" in the FAQ:

What's the "block chain" ?
```
It is the large database that contains all the transactions ever made using Bitcoin. New transactions are gathered up into a group called a block. Each new block references the one before forming a chain.

At present the block chain is about 30Gb and growing every 10 minutes.
```

**Comment by jim618** [comment]
I'll do the edit to the FAQ now

**Comment by jim618** [comment]
Gary, I think you've done the edit the other way way round to what I am proposing.
I am proposing "block chain" to "blockchain"

It has become a compound noun rather than two separate words.

**Comment by jim618** [comment]
We should talk about this so I'll leave it be for now

**Comment by gary-rowe** [comment]
Oops. Misread your proposal with "confirmation bias". I'm of the opinion ([shared by others](http://english.stackexchange.com/questions/41281/blockchain-or-block-chain-double-spend-or-doublespend)) that "blockchain" is an unnecessary compounding and that "block chain" gives more flexibility ("block archive", "block explorer"). Also [Bitcoin.org uses "block chain"](https://bitcoin.org/en/glossary/block-chain) in its glossary as does the [Bitcoin Wiki](https://en.bitcoin.it/wiki/Block_chain).

Agreed that we should take this offline to arrive at a final style choice.

**Comment by jim618** [comment]
Fine by me - if it's on bitcoin.org as 'block chain' let's go with that.
As long as it is one or or the other consistently.

In which case: closing
