### ISSUE TITLE
Mouseover colour on links is illegible

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#221]
I just pulled the latest develop
The mouseover colour for links (Mac/ Safari) is a very light grey on white. Completely illegible.

**Comment by jim618** [comment]
Here is a screenshot whilst the mouse is over 'Trezor' in the right hand side text panel
![screen shot 2015-06-20 at 14 49 57](https://cloud.githubusercontent.com/assets/919427/8267483/b739e6ce-175b-11e5-9498-8b5e06fd0c44.png)

**Comment by gary-rowe** [comment]
Incorrect placement of a comma caused an incorrect override. 

Ready for review and close.

**Comment by jim618** [comment]
Fixed. Closing.
