### ISSUE TITLE
Windows sizing for promo banner 

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#222]
The promo banner does not switch into its smaller sizes at the correct width on Windows. The changeover occurs about 10px too late leading to a staggered menu bar.

Works fine on OS X.

**Comment by gary-rowe** [comment]
Adjusted limits. Verify on Windows machine with FF.

Ready for review and close.

**Comment by jim618** [comment]
Tested that there is no regression on Mac/Safari, Mac/Firefox, Mac/Chrome

Closing.
