### ISSUE TITLE
Change Trezor affiliate link to a=multibit.org

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#223]
As per comment from Martin Sip.
This link usage is clearer.

**Comment by jim618** [comment]
Updated all references of old affiliate link to new. Checked works correctly.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Has this been added to MultiBit HD as well?

**Comment by jim618** [comment]
Nope not yet

**Comment by gary-rowe** [comment]
Verified working. Promo code is automatically filled in to the payment screen.

Closing.
