### ISSUE TITLE
Move MultiBit Classic releases to releases/multibit-classic

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#224]
Currently we have all the MBHD releases in releases/multibit-hd but the MB Classic installers are all in releases.

It would be neater if we move the Classic installers to release/multibit-classic

**Comment by gary-rowe** [comment]
Agreed. Should be a trivial change, and external linkers should probably update anyway. This will also pave the way for the Install4j updates.xml targeting future Classic releases.

**Comment by gary-rowe** [comment]
This needs to be done in concert with a site push reflecting the new locations throughout.

**Comment by gary-rowe** [comment]
I've copied the existing MultiBit Classic releases into the required `multibit-classic` subfolder. When the updated links in the site go live the top level directories can be safely removed with something like `rm -Rf multibit-0*`

**Comment by gary-rowe** [comment]
Links to MultiBit Classic updated throughout.

Ready for review and close.

**Comment by jim618** [comment]
Checked all binaries and links use the 'multibit-classic' subdirectory.
Closing.
