### ISSUE TITLE
Add size of download to buttons

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#225]
Would be useful to indicate the approximate size of the download to users in advance of them starting even though ~30Mb is reasonable by today's broadband standards.

**Comment by jim618** [comment]
I think 30 MB is nothing to worry about now.
Putting it on the buttons makes them look a bit nerdy and unfriendly I think.

At the moment they are big friendly icons, including a dashing image of Tux.

**Comment by gary-rowe** [comment]
Agreed. I'll move this into graveyard.
