### ISSUE TITLE
MultiBit HD Contacts Menu Option

### ISSUE THREAD

**Issue by soslug** [bitcoin-solutions/multibit-website#226]
Not an Issue a such just an observation, but given you have a Contacts Menu selection why not incorporate messaging along with the addition of new contacts, BitMessage already uses Bitcoin protocol and would be a very versatile out of the box solution. It would also do away with email for very short messages. It's like a very secure twitter account.

**Comment by gary-rowe** [comment]
Thanks for the feedback @soslug. Since this is a MultiBit HD client issue I've copied this issue into the MultiBit HD issue database for you. You can follow the reference above and continue watching progress.

Closing this one.
