### ISSUE TITLE
Add a section on Bitcoin ATMs in the Community section

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#228]
For instance: http://coinatmradar.com

**Comment by jim618** [comment]
Added coinatmradar.com to community page.
Also removed 'how to buy bitcoin' link as it has morphed into a list of exchange prices which does not help a newbie obtain bitcoin.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Made some minor edits ("fiat" -> "national currency" etc). Good to go.

Closing.
