### ISSUE TITLE
Help is referencing wrong URL for installer

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#229]
Seeing this in the HTTPD logs:

File does not exist: /var/www/html/releases/multibit-0.1.0, referer: https://multibit.org/en/help/v0.5/help_installing.html

The HD installers are in /releases/multibit-hd/multibit-0.1.0

**Comment by gary-rowe** [comment]
The `.ftl` needed updating to differentiate between HD and Classic versions. Added correct references and "Classic" in places.

Ready for review and close.

**Comment by jim618** [comment]
Checked Classic and HD download URLs are correct.
Closing
