### ISSUE TITLE
transaction issue

### ISSUE THREAD

**Issue by chris56a** [bitcoin-solutions/multibit-website#230]
wallet id "1H1ZfMM16pvyNtUq5huBseQrRR7Kr9KgnB" is my multiunit address your macbook app shows i have around .10 cents but the blockchain shows i have 1.17 btc this issue was on june/ 27/2015 now its the next day and i still don't see anything i've tried resetting the blockchain etc

**Comment by gary-rowe** [comment]
This is the MultiBit website issue database (for documentation errors and so on).

As a first step, can you read either the MultiBit Classic or HD [help articles](https://multibit.org/help.html) depending on which product you're using and then raise a support issue on their respective issue databases (linked in the Help) if they don't resolve your issue.

**Comment by chris56a** [comment]
didn't really get an answer from the articles,and since theres no number or anything to call i came here...

**Comment by chris56a** [comment]
issues solved nvm

**Comment by gary-rowe** [comment]
OK, glad you were able to resolve it. Usually trying the Reset Blockchain option several times does the trick.

Closing.
