### ISSUE TITLE
Add a robots.txt to stop crawling of binaries

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#234]
I think crawlers are downloading the out of date binaries we provide.
This just eats bandwidth.

Perhaps a robots.txt file where we exclude the releases dir would lessen this

**Comment by gary-rowe** [comment]
We already have a `robots.txt` file, but it wasn't filled out very much. I've added more detail.

Ready for review and close.

**Comment by jim618** [comment]
Should help our bandwidth a little.
Closing
