### ISSUE TITLE
Add note to OS X install page indicating the minimum supported version

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#235]
Due to Java 1.7.0_80 RE compatibility we can only go back as far as 10.7.3 (Lion). This was released in July 2011. Upgrades to OS X are generally free (e.g. Yosemite) so we have no strong need to support older versions.

We should also point people to the App Store where they can get the upgrade (5Gb download typically).

**Comment by gary-rowe** [comment]
Added note. Ready for review and close.

**Comment by jim618** [comment]
LGTM
