### ISSUE TITLE
Website links on site point to jim618/multibit-website and then redirects

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#238]
As per title.
It looks a bit odd that the link at the bottom of the website is:
https://github.com/jim618/multibit-website/issues/new

and then it redirects to bitcoin-solutions/multibit-website

**Comment by gary-rowe** [comment]
Removed jim618 references throughout.

Ready for review and close.

**Comment by jim618** [comment]
Checked help links point to bitcoin-solutions git repo now.
Closing.
