### ISSUE TITLE
Where are wallet and backup files stored?

### ISSUE THREAD

**Issue by starrychloe** [bitcoin-solutions/multibit-website#244]
I already backup my files. I need to know if the wallet files are stored in \Program Files\ or %APPDATA%\. This page tells goes into so much detail without revealing this simple piece of information: https://multibit.org/en/help/hd0.1/backups.html

**Comment by jim618** [comment]
It varies by operating system where the application data IS, but the wallets are always stored in there.

The easiest way to see where the backups are is to look in the Manage wallet | Wallet dashboard and see the application directory and wallet directory (within it). The rolling and local zip backups backups are stored in that wallet directory (in sub directories). The cloud backups are stored wherever you have the cloud backup directory set to.

**Comment by gary-rowe** [comment]
@starrychloe I think you need the [File descriptions](https://multibit.org/en/help/hd0.1/files.html) article.

**Comment by gary-rowe** [comment]
Since there is nothing to do here, I'll close this issue.
