### ISSUE TITLE
Add direct link to Classic downloads on landing page

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#245]
I think we should have a direct link to the MB Classic downloads (http://multibit.org/releases.html) on the landing page.

Though HD is our primary offering, there are a lot of Classic users out there and I think it is a bit tricky for people to find the link to the release at the moment.

Perhaps change the current:

To get a full list of versions go to the download section.

(at the bottom)
to

Looking for MultiBit Classic ? Downloads available here.

**Comment by gary-rowe** [comment]
Added to main page. This may also help SEO for MultiBit Classic.

Ready for review and close.

**Comment by jim618** [comment]
Looks fine. Closing.
