### ISSUE TITLE
Remove Tor support text

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#248]
As Tor support is removed in 0.1.3 it also needs to be removed from the help files

**Comment by jim618** [comment]
I have changed the labs.html so that there is now a mention of Tor support being dropped:

```
<h4>Tor is no longer supported in MultiBit HD</h4>

<p>We have dropped Tor support from MultiBit HD 0.1.3 onwards. Unfortunately this functionality has proven too unreliable for production code. If and when this becomes more solid then we will add this functionality back into MultiBit HD.</p>
```

Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks fine. It's a shame that it will take so much effort to get the reliability up to production levels. I'll make a note to revisit this once Orchid 1.2 is properly integrated into Bitcoinj. 

Paging @mikehearn to let you know about this situation. (We know you're busy with other things so no pressure).

**Comment by mikehearn** [comment]
I don't recall any bugs being filed? What's the reliability issue?

**Comment by gary-rowe** [comment]
There's quite a bit of detail in the MultiBit HD issue: https://github.com/bitcoin-solutions/multibit-hd/issues/633

We've not yet filed a bug report into bitcoinj. We can do that tomorrow so you've got all the details.
