### ISSUE TITLE
Remove 'To get a full list of versions go to the download section.' - already on Landing page

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#249]
We now have two sentences at the bottom of the landing page about 'more downloads'.
One for the MBHD downloads, one for Classic.

I think we should remove the MBHD downloads one:
"To get a full list of versions go to the download section."

And just have the Classic one.

We already have the 'Downloads' button in the menu bar and it is a bit confusing having two similar 'download linky' sentences.

**Comment by jim618** [comment]
I have removed the 'non-Classic' link.
See what you think. I think it is clearer for Classic users.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Looks fine. We already have a primary download link at the top, and the buttons. Having a direct link for Classic on the front page shows continued support for our secondary product.

I've done appropriate edits in ES, FR and ZH locales.

Closing.
