### ISSUE TITLE
Add support for Russian landing page

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#250]
Traffic analysis indicates Russia should be supported.

**Comment by gary-rowe** [comment]
To verify, set your locale switcher to Russian language (e.g. ru or ru_RU).

Ready for review and close.

**Comment by jim618** [comment]
Looks good.
Screenshot:

![screen shot 2015-08-23 at 11 23 48](https://cloud.githubusercontent.com/assets/919427/9427853/870788c0-4989-11e5-9bf1-2b5d50c3ddd3.png)
