### ISSUE TITLE
Add article for 0.1.3 release

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#251]
Require updates throughout to cover 0.1.3.

**Comment by gary-rowe** [comment]
Pushed first draft of article. Ready for initial review.

**Comment by jim618** [comment]
I have done a few tweaks and added a screenshot of the Greek translation.
Also added the article to the main blog index.

Checked main download artifact is at 0.1.3 and download page updated.

Awaiting re-review by @gary-rowe and closing

**Comment by gary-rowe** [comment]
Changes look good to me.

Closing.
