### ISSUE TITLE
Download Mirror

### ISSUE THREAD

**Issue by BurntRouter** [bitcoin-solutions/multibit-website#260]
Downloads seem to be lacking in speed harshly. I went to download Multibit (new operating system) and it was a painful 16kb/s and that was after I had to restart the download. I'm also noticing a slow load time. To reduce some stress I'd like to offer you a mirror. My website is http://burntrouter.info
I'll hook you up will full FTP access to your multibit download directory and such. Just trying to help out. Let me know!

**Comment by gary-rowe** [comment]
Thanks for the offer of a mirror, but that would be against our [privacy policy](https://multibit.org/privacy.html). 

Also we've not seen any slow downloads in our logs (a typical broadband result is >500 Kb/s). 

Closing.
