### ISSUE TITLE
Atom feed had 'v0.1.4' release article in triplicate

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#263]
Probably due to the v0.1.4 release date being bumped twice, there are 3 Atom feed references to the same article.

Looking in Vienna I see 3 entries for the same article.

**Comment by jim618** [comment]
There are x2 repeats of several of the other articles (in Vienna) too e.g. 'Bitcoin network stress test' appears twice

**Comment by jim618** [comment]
Talkin go Gary this will almost certainly be due to code in AtomBuilder

**Comment by jim618** [comment]
I have added code into AtomBuildFeeder so that articles that are in the atom.xml but have been deleted/ renamed are removed.

Previously there were 3 entries to the MBHD 0.1.4 release. Now there is one.
Screenshot:

![screen shot 2015-10-29 at 16 28 23](https://cloud.githubusercontent.com/assets/919427/10824918/757069c8-7e5a-11e5-97ce-3f8a930118be.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
