### ISSUE TITLE
Add Help section for "+Unconfirmed" message 

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#264]
A few error reports have indicated a need to address this in the help.

Suggest: https://multibit.org/en/help/hd0.1/request-bitcoin.html

**Comment by jim618** [comment]
I have added more detail to the request-bitcoin.html, including an explanation of the '+Unconfirmed".

Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks good to me. Closing.
