### ISSUE TITLE
Add Help section for instructions on verifying payment has been made to a seller

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#265]
User feedback indicates that clearer instructions on how to check payment has been made (i.e. using a block explorer) would be useful.

Suggest: https://multibit.org/en/help/hd0.1/payments.html

**Comment by jim618** [comment]
I have added more detail (to the request-bitcoin.html), including an explanation of the transaction wizard and using a block explorer

Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks good to me. Closing.
