### ISSUE TITLE
There is no help for creating additional wallets

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#267]
The 'Create wallet' help only covers creating the very first wallet.
There is no mention that the user can create additional wallets, and switch between them.

**Comment by gary-rowe** [comment]
There is a short hint in the help article, but I've taken this opportunity to flesh it out a little more and add a link to our [YouTube tutorial](https://www.youtube.com/watch?v=3B6xrfoPqPg) about it.

Ready for review and close.

**Comment by jim618** [comment]
LGTM.
Closing
