### ISSUE TITLE
Need new screenshots for MBHD 0.2.0

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#268]
The sidebar has changed in MBHD v0.2.0 so we need new screenshots for the website

**Comment by jim618** [comment]
Added screenshots for the index page

**Comment by gary-rowe** [comment]
Good screen (and mug) shots there. Will need another one for the help.html to show the 0.2 layout.

**Comment by jim618** [comment]
Added screenshot for help screen. Ensured MBHD and Classic are same size.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Look fine to me. Closing.
