### ISSUE TITLE
Add disambiguation note to MultiBit Classic download page

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#271]
A new Bitcoin client called Bitcoin Classic is being introduced and the authors have asked us to ensure that there is no confusion in people's minds between it and MultiBit Classic.

Suggested text is:

MultiBit Classic is not dependent on, or affiliated with, the similarly named Bitcoin Classic full node project. Like MultiBit HD, MultiBit Classic works directly with the Bitcoin network and by extension all full nodes that run the Bitcoin protocol.

**Comment by jim618** [comment]
Yeah it is an unfortunate name collision but 'Classic' is well used in marketing to distinguish the 'old' thing from the 'new' thing so we will just have to live with it. I would simplify the text to:

"MultiBit Classic is not related to the Bitcoin Classic full node project. MultiBit Classic works directly with any Bitcoin full node"

Suggest we put it on the landing page, near the comment about where the MultiBit Classic downloads are. Or on the MultiBit Classic downloads page.

**Comment by gary-rowe** [comment]
Let's go with the MultiBit Classic downloads page - that way we can avoid translating it multiple times.

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by jim618** [comment]
Reads fine so closing.
Note that I haven't pushed this change to multibit.org yet.
