### ISSUE TITLE
Create new help for 0.2.0

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-website#273]
There needs to be a new version of help for the 0.2.0 code, including Buy/ Sell
It needs to be a new directory in the help as we use the major version to differentiate versions

**Comment by jim618** [comment]
I have duplicated the 0.1 help into a 0.2 folder and written a 'Buy/ Sell bitcoin' help page.

The screenshots are still the v0.1 images - this is covered in #268.

Awaiting reviewing and closing

**Comment by gary-rowe** [comment]
Bounced back to ensure code review of minor updates.

**Comment by jim618** [comment]
Checked content pages crosslinking.

Closing
