### ISSUE TITLE
External help from v0.2.0 is not getting resolved (404)

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-website#279]
URLs of the form https://multibit.org/hd0.2/buy-sell-bitcoin.html are not correctly resolving.

It appears that the `PublicHD0_2Resource` has not been implemented

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by jim618** [comment]
I've rebuilt this and deployed it to multibit.org.
Also checked that MBHD 0.2.0 correctly displays the live help, both in app and in the external browser.

Closing
