### ISSUE TITLE
I need Help!

### ISSUE THREAD

**Issue by Supevaara** [bitcoin-solutions/multibit-website#286]
I need help when my wallet password is forgotten, and I have not saved the password to anything. Who could open my wallet? there is money 1BTC
preferably by e-mail answer: super47@hotmail.fi

**Comment by gary-rowe** [comment]
This is the issue database for the website, rather than the wallet.

However, you can always cover your password so long as you have your wallet words. Simply follow the instructions here: https://multibit.org/en/help/hd0.2/restore-password.html

**Comment by gary-rowe** [comment]
Closing since the help shows what to do.
