### ISSUE TITLE
Recieve bitcoins

### ISSUE THREAD

**Issue by abhisheksnspisa** [bitcoin-solutions/multibit-website#292]
Why do I need to enter an amount when I ask for an address to receive BitCoin? What if the person with that address sends me more or less than the entered amount of BitCoins?

**Comment by gary-rowe** [comment]
This is the issue database for reporting issues about the content of the MultiBit website, not for general support questions.

That said, you can choose to leave the amount field empty when requesting. It is present to allow a specific amount to be paid against a request, possibly over multiple payments by the payer.
