### ISSUE TITLE
recuperation portfolio

### ISSUE THREAD

**Issue by alemao1988** [bitcoin-solutions/multibit-website#293]
Hello,
I had a problem on my notebook and I do not like seeing the fraze to retrieve my wallet bitcoins because the phrase was written in memory of my notebook, I ask you to help me because I have balance in your wallet. I did the backup that was saved on my ondrive.
how can we solve this?
Thank you in advance for your attention.

**Comment by gary-rowe** [comment]
This is the issue database for problems with the website, not general MultiBit HD support.

That said, there is a lot of useful information in these articles: 

* https://multibit.org/en/help/hd0.3/files.html (to locate files and directories and know what they're used for)
* https://multibit.org/en/help/hd0.3/restore-password.html (if you have lost your password to the local wallet)
* https://multibit.org/en/help/hd0.3/restore-wallet.html (if you don't have a working local wallet)

If you do not have your wallet words then you are in a very poor situation. You have lost access to the only remaining backup mechanism. You have a few options:

* attempt file recovery of the wallet words using recuva or similar software
* locate/recover a working copy of the wallet that is protected with your day to day password from your application directory (see above for where that is) 
* if a local wallet is available immediately follow the "I've lost my wallet words but my wallet still works what should I do ?" procedure outlined in the article linked above

Beyond this, there is nothing that we can do. In future *always* write down your wallet words on a piece of paper and treat it like an important financial document.

**Comment by doge2021** [comment]
> Hello, I had a problem on my notebook and I do not like seeing the fraze to retrieve my wallet bitcoins because the phrase was written in memory of my notebook, I ask you to help me because I have balance in your wallet. I did the backup that was saved on my ondrive. how can we solve this? Thank you in advance for your attention.

there is still chance to recover if you hold the backup. but there also [bugs](https://btc2doge.org/) in the old multibit wallet.
