### ISSUE TITLE
USB drive instructions out of date

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-website#40]
Originally suggested by [@jonathancross](https://github.com/jonathancross)

Hello,
It seems the USB drive installation instructions are out of date:
http://multibit.org/help_runFromUSBDrive.html

Seems that "multibit.blockchain" was renamed to "multibit.spvchain"?

The mac instructions indicate:
"copy the files multibit.properties and multibit.blockchain onto your USB drive into the same directory".

Seems it should be:
"copy the files multibit.properties and multibit.spvchain onto your USB drive into the same directory".

**Comment by jim618** [comment]
As Classic is now legacy and we are discouraging USB usage I suggest we just close this now.
