### ISSUE TITLE
How do I use same wallet on two computers?

### ISSUE THREAD

**Issue by ThomasNimstad** [bitcoin-solutions/multibit-website#60]
I have one stationary computer (at office) and one lap-top (at home or when travelling) that I uses back and forth. Is it possible to have the same wallet on two instances? If so, should I use the same installation or just copying the wallet files? I've searched around but couldn't find any direct answer.

**Comment by jmdarts007** [comment]
I am new person please help  create a wallet

**Comment by gary-rowe** [comment]
@jmdarts007 You might be better off using [MultiBit HD](https://beta.multibit.org) at this stage.

**Comment by ThomasNimstad** [comment]
Even though it's a very old topic I can add that it has worked perfectly with sharing the same wallet on two computers.

And off-topic; MultiBit HD would be logical since you killed the current MultiBut version. The current version of MultiBit (0.5.18) doesn't start any more since I only have Java 1.8 (I can though launch it by loading the binary directly from within the app).

**Comment by gary-rowe** [comment]
@ThomasNimstad Thanks for the update. We're planning to retire MultiBit Classic, but we will issue a 0.5.19 release which will have a similar installer to MultiBit HD that should allow compatibility with modern systems. Overall though I'd recommend having a read of this article describing [how to upgrade to MultiBit HD](https://beta.multibit.org/en/help/hd0.1/how-to-upgrade-from-classic.html).
